// Generated by CoffeeScript 1.6.3
(function() {
  var root;

  root = typeof exports !== "undefined" && exports !== null ? exports : this;

  root.getIoInfo = function() {
    return [
      {
        name: 'io1.1',
        pin: '1',
        id: '1',
        activemode: 'Pull Up',
        currentColor: '#FF3300'
      }, {
        name: 'io2.1',
        pin: '1',
        id: '2',
        activemode: 'Pull Up',
        currentColor: '#FF3300'
      }, {
        name: 'io3.1',
        pin: '1',
        id: '3',
        activemode: 'Pull Up',
        currentColor: '#FF3300'
      }
    ];
  };

}).call(this);
