// Generated by CoffeeScript 1.6.3
(function() {
  var app, fs, generateChartData, getUpdateData, io, rollDice, server, __dirname;

  app = require('express')();

  server = require('http').createServer(app);

  io = require('socket.io')(server);

  fs = require('fs');

  __dirname = '';

  server.listen(8000, function() {
    return console.log('listening');
  });

  app.get('/', function(req, res) {
    console.log('recieved request');
    return fs.readFile(__dirname + '../index.html', function(err, data) {
      if (err) {
        console.log('error');
        res.writeHead(500);
        return res.end('error loading index.html');
      } else {
        console.log('success');
        res.writeHead(200);
        return res.end(data);
      }
    });
  });

  rollDice = function() {
    return Math.floor(Math.random() * (0 + 200 - 1)) + 1;
  };

  generateChartData = function() {
    var lineChartData;
    return lineChartData = [
      {
        label: 'test1',
        datapoints: [
          {
            timestamp: 1383230753238,
            count: rollDice()
          }, {
            timestamp: 1383230784165,
            count: rollDice()
          }, {
            timestamp: 1383230821680,
            count: rollDice()
          }
        ]
      }, {
        label: 'test2',
        datapoints: [
          {
            timestamp: 1383230753238,
            count: rollDice()
          }, {
            timestamp: 1383230784165,
            count: rollDice()
          }, {
            timestamp: 1383230821680,
            count: rollDice()
          }
        ]
      }, {
        label: 'test3',
        datapoints: [
          {
            timestamp: 1383230753238,
            count: rollDice()
          }, {
            timestamp: 1383230784165,
            count: rollDice()
          }, {
            timestamp: 1383230821680,
            count: rollDice()
          }
        ]
      }
    ];
  };

  getUpdateData = function(timestamp) {
    return [[timestamp, rollDice()], [timestamp, rollDice()], [timestamp, rollDice()]];
  };

  io.on('connection', function(socket) {
    var int, timestamp;
    timestamp = 1383230821680;
    /* this is just for testing it needs to be compiled with actual state of each pin  this could be done via a local database*/

    socket.emit('init', generateChartData());
    console.log('connected');
    int = setInterval(function() {
      timestamp += 10000;
      socket.emit('update', getUpdateData(timestamp));
      return console.log('update Sent');
    }, 10000);
    socket.on('updateComponent', function(data) {});
    return socket.on('disconnect', function() {
      return clearInterval(int);
      /* here is where you pu in all the magic to update the network device*/

    });
  });

}).call(this);
